# This file was generated by GoReleaser. DO NOT EDIT.
cask "hive" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "hive"], chdir: ".", must_succeed: false
    end
  end

  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "13424872f295d3d18b4886619f392e0d8ebc1d2d99c10c182b828d49f917a983"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d4ae84a4b53b312e10b887d38c81d9adf79e0dd94e813f5b62d6ce23379b52ae"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "26c756c5eddd6237f990a1254d5930bec845b622dff2cb3cd7b31ea04fe41818"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "edb9c693647d21692d88cbbb6af33f0594d73796303307920c5ddd1defac4ba0"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hive"
  desc "One tree of all your coding-agent sessions"
  homepage "https://github.com/SadriShehu/hive"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "hive"

  # No zap stanza required

  caveats <<~EOS
    Run `hive install` to connect every agent found on your PATH.
  EOS
end
