# This file was generated by GoReleaser. DO NOT EDIT.
cask "hive" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "1c41e3e7de12374a46207ac1f128130c75892d53366ee2e96f009d89cb5117eb"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4262b47d306710916cd89bae5e78a320940608982ea8b7f49ef53971afc469c6"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5e7ee14073b912168749742b29e3b8e9c1ff67aaa16a8d99d03fc3e24d77ca75"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b6e59c6a7312918dee8f25bbdd4f101d2ef1014f220177d8d360c5058dc396ba"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hive"
  desc "One tree of all your coding-agent sessions"
  homepage "https://github.com/SadriShehu/hive"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "hive"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hive"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `hive install` to connect every agent found on your PATH.
  EOS
end
