# This file was generated by GoReleaser. DO NOT EDIT.
cask "hive" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "0d197a00f532296274d065172ea83723e983b0359b8379c6ca593df2e08fd310"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "31bae56169ee699e9b15aa95b197a696cc700ae6fc605514f747656e3b2df752"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "beca1e6971d28dc96a9d87051694b08abaa043dd700e52b4114fe9f038889c83"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "26d767457341d237594d3e3638bf0da48195c2ed271ac64ad6ad938b146a0f5f"
      url "https://github.com/SadriShehu/hive/releases/download/v#{version}/hive_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hive"
  desc "One tree of all your coding-agent sessions"
  homepage "https://github.com/SadriShehu/hive"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "hive"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hive"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `hive install` to connect every agent found on your PATH.
  EOS
end
